-- MySQL Script generated by MySQL Workbench
-- Wed Jul 22 00:02:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema revistaspaciodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema revistaspaciodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `revistaspaciodb` DEFAULT CHARACTER SET utf8 ;
USE `revistaspaciodb` ;

-- -----------------------------------------------------
-- Table `revistaspaciodb`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revistaspaciodb`.`Ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `Ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`idCiudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revistaspaciodb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revistaspaciodb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(100) NOT NULL,
  `Usermail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(100) NULL,
  `CreateTime` DATE NOT NULL DEFAULT NOW(),
  `UpdateTime` DATE NOT NULL DEFAULT NOW(),
  `Ciudad_idCiudad` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `Username_UNIQUE` (`Username`) ,
  UNIQUE INDEX `Usermail_UNIQUE` (`Usermail`) ,
  FOREIGN KEY (`Ciudad_idCiudad`)  REFERENCES `revistaspaciodb`.`Ciudad` (`idCiudad`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revistaspaciodb`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revistaspaciodb`.`Perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(32) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revistaspaciodb`.`Usuario_has_Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revistaspaciodb`.`Usuario_has_Perfil` (
  `Usuario_idUsuario` INT NOT NULL,
  `Perfil_id` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Perfil_id`),
  FOREIGN KEY (`Usuario_idUsuario`)  REFERENCES `revistaspaciodb`.`Usuario` (`idUsuario`) ,
  FOREIGN KEY (`Perfil_id`) REFERENCES `revistaspaciodb`.`Perfil` (`id`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revistaspaciodb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revistaspaciodb`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revistaspaciodb`.`Entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revistaspaciodb`.`Entrada` (
  `idEntrada` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NULL,
  `Contenido` TEXT NULL,
  `Fecha` DATETIME NULL,
  `Imagen` VARCHAR(255) NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`idEntrada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revistaspaciodb`.`Entrada_has_Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revistaspaciodb`.`Entrada_has_Categoria` (
  `Entrada_idEntrada` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`Entrada_idEntrada`, `Categoria_idCategoria`),
  FOREIGN KEY (`Entrada_idEntrada`) REFERENCES `revistaspaciodb`.`Entrada` (`idEntrada`) ,
  FOREIGN KEY (`Categoria_idCategoria`) REFERENCES `revistaspaciodb`.`Categoria` (`idCategoria`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revistaspaciodb`.`Usuario_has_Entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revistaspaciodb`.`Usuario_has_Entrada` (
  `Usuario_idUsuario` INT NOT NULL,
  `Entrada_idEntrada` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Entrada_idEntrada`),
  FOREIGN KEY (`Usuario_idUsuario`) REFERENCES `revistaspaciodb`.`Usuario` (`idUsuario`) ,
  FOREIGN KEY (`Entrada_idEntrada`) REFERENCES `revistaspaciodb`.`Entrada` (`idEntrada`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
